//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert_Category
    {
        public Advert_Category()
        {
            this.Advert = new HashSet<Advert>();
        }
    
        public int ACCode { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<Advert> Advert { get; set; }
    }
}
