//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public Advert()
        {
            this.Favorites = new HashSet<Favorites>();
            this.Images_To_Advert = new HashSet<Images_To_Advert>();
        }
    
        public int ACode { get; set; }
        public Nullable<int> UCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CCode { get; set; }
        public Nullable<int> ACCode { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string History { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Advert_Category Advert_Category { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<Images_To_Advert> Images_To_Advert { get; set; }
    }
}
