//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int CCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> CoCode { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
