//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.City = new HashSet<City>();
        }
    
        public int CoCode { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<City> City { get; set; }
    }
}
