//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NCode { get; set; }
        public Nullable<int> AuthorCode { get; set; }
        public Nullable<int> RecipientCode { get; set; }
        public string Content { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
