//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmekayEntities : DbContext
    {
        public SmekayEntities()
            : base("name=SmekayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advert> Advert { get; set; }
        public DbSet<Advert_Category> Advert_Category { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Favorites> Favorites { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<Images_To_Advert> Images_To_Advert { get; set; }
    }
}
