//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smekay24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Notification = new HashSet<Notification>();
        }
    
        public int UCode { get; set; }
        public Nullable<int> CCode { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> News { get; set; }
        public Nullable<int> Reminders { get; set; }
        public Nullable<int> Notifications { get; set; }
        public string Contacts { get; set; }
        public Nullable<int> Banned { get; set; }
        public Nullable<int> Role { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
    }
}
